# Site settings
title: Edger's Blog
SEOTitle: Edger's Blog
header-img: img/home-bg.jpg
email: 
description: ""
keyword: ""
url: "https://edger.github.io/"              # your host, for absolute URL
baseurl: ""                                     # for example, '/blog' if your blog hosted on 'host/blog'

# Publish posts or collection documents with a future date.
future: true

# SNS settings
RSS: false
weibo_username:     2761043145
# zhihu_username:     
github_username:    Edger
# twitter_username:  
# facebook_username: 
# linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Add wiki page
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

# Disqus settings
# disqus_username: _your_disqus_short_name_

# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
# ba_track_id: [your track id]

# Google Analytics
# ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
# ga_domain: huangxuan.me



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "其犹龙乎，卜他年鲤化蛟腾，尽洗蛮烟蜑雨。"
sidebar-avatar: /img/avatar.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 0              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
        title: "Hux Blog",
        href: "http://huangxuan.me/"
    },{
        title: "Gityuan",
        href: "http://gityuan.com/"
    },{
        title: "码志",
        href: "https://mazhuang.org/"
    },{
        title: "独立",
        href: "https://josephchang10.github.io/chinese-indie-hackers/#"
    },{
        title: "酷壳",
        href: "https://coolshell.cn/"
    },{
        title: "干货集中营",
        href: "https://gank.io/"
    },{
        title: "阮一峰的网络日志",
        href: "http://www.ruanyifeng.com/blog/"
    },{
        title: "贾鹏辉的技术博客官网",
        href: "http://www.devio.org/"
    },{
        title: "Weishu's Notes",
        href: "http://weishu.me/"
    },{
        title: "Tick-tick",
        href: "https://www.liutf.com/"
    }
]
